{
 "title": "ProjektDashboard2",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "EMS - 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "erzeugterStrom_metric", "legendFormat": "__auto" },
    { "expr": "batterie_stand_metric", "legendFormat": "__auto" },
    { "expr": "strom_verbrauch_metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EMS - 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "erzeugterStrom_metric", "legendFormat": "__auto" },
    { "expr": "batterie_stand_metric_s2", "legendFormat": "__auto" },
    { "expr": "strom_verbrauch_metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EMS - 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "erzeugterStrom_metric", "legendFormat": "__auto" },
    { "expr": "batterie_stand_metric_s3", "legendFormat": "__auto" },
    { "expr": "strom_verbrauch_metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Preis im Cents/Kwh",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "strom_preis_metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Eingespeisung (kW) - EMS - 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "eingespeister_strom_metric{job=\"wetter-data\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Einspeisung (kW) - EMS - 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    { "expr": "eingespeister_strom_metric_s2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Einspeisung (kW) - EMS - 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "expr": "eingespeister_strom_metric_s3", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gewinn durch Einspeisung EMS - 1 ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    { "expr": "earning_strom_metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gewinn durch Einspeisung EMS - 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    { "expr": "earning_strom_metric_s2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gewinn durch Einspeisung  EMS - 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    { "expr": "earning_strom_metric_s3", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gekaufter Strom kWh",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    { "expr": "gekaufter_strom_metric ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "gekaufter Strom kWh  EMS - 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "targets": [
    { "expr": "gekaufter_strom_metric_s2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "gekaufter Strom EMS - 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    { "expr": "gekaufter_strom_metric_s3", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ausgabe Strom EMS - 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "targets": [
    { "expr": "ausgabe_strom_metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ausgabe Strom - EMS - 2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "targets": [
    { "expr": "ausgabe_strom_metric_s2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ausgabe Strom EMS - 3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    { "expr": "ausgabe_strom_metric_s3", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netto Gewinn - Cents - EMS - 1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gewinn_metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netto Gewinn Cents - EMS - 2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gewinn_metric_s2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Netto Gewinn - Cents - EMS - 3",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gewinn_metric_s3", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperutur - celcius",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "temperatur_metric{job=\"wetter-data\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}