global:
  scrape_interval: 10s
  #evaluation_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]


  - job_name: 'wetter-metrics'
    metrics_path: /api/wetter/metrics
    static_configs:
      - targets: ['localhost:5001']
        labels:
          instance: 'wetter'
          job: 'wetter-data'

