name: Node.js CI/CD with Docker

on:
  push:
    branches:
      - masterNew  # Change this to your main branch name

jobs:
    
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: create env file
      run: |
        touch .env
        echo OPEN_WEATHER_API=${{ secrets.WETTER_KEY }} >> .env
        echo NREL_PVWATT_KEY=${{ secrets.STROM_KEY }} >> .env
        echo PREISE_API_KEY=${{ secrets.PREIS_KEY }} >> .env
        echo ${{process.env.OPEN_WEATHER_API}}

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  
        
    - name: Install dependencies
      run: npm install
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/prosumer_app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/prosumer_app:latest
